# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

---
steps:
  - label: ":windows: Windows Build"
    agents: { queue: windows }
    plugins: [$CI_TOOLKIT, $NVM_PLUGIN]
    command: |
      echo "~~~ Setup code signing"
      .buildkite/commands/setup_windows_code_signing.ps1

      echo "~~~ Install dependencies"
      bash .buildkite/commands/install_node_dependencies.sh

      echo "~~~ Build renderer"
      npm run build:once

      echo "~~~ Build Windows artifact"
      npm run dist:win
    artifact_paths:
      - dist\*.exe
      - dist\*.msi
