# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

---
steps:
  - label: ":windows: Windows Build"
    agents: { queue: windows }
    plugins:
     - automattic/a8c-ci-toolkit#5.5.0: ~
     - automattic/nvm#0.6.0:
         version: 'v20'
    command: |
      echo "~~~ Setup code signing"
      .buildkite/commands/setup_code_signing.ps1

      echo "~~~ Install dependencies"
      bash .buildkite/commands/install_node_dependencies.sh

      echo "~~~ Build renderer"
      npm run build:once

      echo "~~~ Build Windows artifact"
      npm run dist:win
    artifact_paths:
      - dist\*.exe
      - dist\*.msi
