#!/bin/bash -eu

# This file is `source`'d in CI before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

export CI_TOOLKIT=automattic/a8c-ci-toolkit#5.5.0
export NVM_PLUGIN=automattic/nvm#0.6.0
export IMAGE_ID=xcode-26.0
